#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh --shades

bspc monitor eDP -d I II III IV V VI VII VIII IX X

bspc config focused_border_color "#ffffff"
bspc config border_width 2
bspc config window_gap 20

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc rule -a "Apache NetBeans IDE 12.3" desktop='^3'
#bspc rule -a "Thunar" desktop='^2'
#bspc rule -a "Firefox" desktop='^1'
#bspc rule -a "Chromium" desktop='^1'
#bspc rule -a "Alacritty"
#bspc rule -a Program desktop='^N' state=floating follow=on
